name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Boost download
      run: sudo sudo apt-get install libboost-all-dev
    - name: make
      run: make
    - name: make test
      run: make test
    - name: make runtest
      run: make runtests
